scrolling:
  history: 10000
font:
  normal:
    family: "Sauce Code Pro Nerd Font"
    # family: monospace
    style: Medium
  size: 6

# Colors (Doom One)
# https://github.com/eendroroy/alacritty-theme/blob/master/themes/doom_one.yml
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'

shell:
  program: zsh

# disable manual terminal flow-control,
# which I have never intentionally used.
key_bindings:
  - { key: S, mods: Control, action: None }
  - { key: Q, mods: Control, action: None }
